### ISSUE TITLE
Fatal error: Uncaught Error: Class 'WP2StaticCopy\Controller' not found

### ISSUE THREAD

**Issue by twardoch** [leonstafford/wp2static-addon-directory-deployment#1]
I get this when trying to use the compiled version from this repo. My own original code works fine. 

```
Fatal error: Uncaught Error: Class 'WP2StaticCopy\Controller' not found in $MY_WORDPRESS_PATH/wp-content/plugins/wp2static-addon-directory-deployment/wp2static-addon-directory-deployment.php:27 Stack trace: #0 $MY_WORDPRESS_PATH/wp-content/plugins/wp2static-addon-directory-deployment/wp2static-addon-directory-deployment.php(41): run_wp2static_addon_copy() #1 $MY_WORDPRESS_PATH/wp-admin/includes/plugin.php(2288): include_once('/home/fontlabc/...') #2 $MY_WORDPRESS_PATH/wp-admin/plugins.php(192): plugin_sandbox_scrape('wp2static-addon...') #3 {main} thrown in $MY_WORDPRESS_PATH/wp-content/plugins/wp2static-addon-directory-deployment/wp2static-addon-directory-deployment.php on line 27
```

**Comment by markeclaudio** [comment]
You have to use this: https://github.com/elementor/wp2static-addon-directory-deployment/blob/master/release/wp2static-addon-copy.zip
